In [78]:
from pathlib import Path
import cv2
import pandas as pd

In [75]:
raw_dir=Path("../data/raw")
real_videos = list((raw_dir / "original").glob("*.mp4"))
fake_videos=list((raw_dir / "Deepfakes").glob("*.mp4"))

In [76]:
print(f"real count: {len(real_videos)}")
print(f"fake count: {len(fake_videos)}")

real count: 1000
fake count: 1000

In [77]:
print(type(real_videos[0]))
cap = cv2.VideoCapture(str(real_videos[0]))

<class 'pathlib.PosixPath'>

In [42]:
print("fps ", cap.get(cv2.CAP_PROP_FPS))
print("frame count ", cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
#cap.release()

fps  0.0
frame count  0.0

In [64]:
fourcc = int(cap.get(cv2.CAP_PROP_FOURCC))
codec = "".join([chr((fourcc >> 8*i) & 0xFF) for i in range(4)])

In [65]:
print(codec)

h264

In [69]:
real_df=pd.read_csv("../data/raw/csv/original.csv")
fake_df=pd.read_csv("../data/raw/csv/Deepfakes.csv")

In [68]:
real_df.head()

,Unnamed: 0,File Path,Label,Frame Count,Width,Height,Codec,File Size(MB)
0,0,original/000.mp4,REAL,396,640,480,h264,0.85
1,1,original/001.mp4,REAL,460,1280,720,h264,2.78
2,2,original/002.mp4,REAL,693,1280,720,h264,2.02
3,3,original/003.mp4,REAL,303,640,480,h264,0.58
4,4,original/004.mp4,REAL,309,1280,720,h264,1.20

In [70]:
fake_df.head()

,Unnamed: 0,File Path,Label,Frame Count,Width,Height,Codec,File Size(MB)
0,0,Deepfakes/000_003.mp4,FAKE,396,640,480,h264,0.85
1,1,Deepfakes/001_870.mp4,FAKE,460,1280,720,h264,2.74
2,2,Deepfakes/002_006.mp4,FAKE,693,1280,720,h264,1.98
3,3,Deepfakes/003_000.mp4,FAKE,303,640,480,h264,0.57
4,4,Deepfakes/004_982.mp4,FAKE,309,1280,720,h264,1.19

In [91]:
print(fake_df['Frame Count'].mean())
fake_df.groupby(["Width","Height"]).size()

509.128

Width  Height
272    480         1
454    480         1
586    480         1
598    480         2
600    480        48
602    480         1
632    480         1
636    480         1
640    480       257
642    480         2
644    480         1
654    480        20
656    480        66
658    480         2
712    480         1
720    480        27
800    480         1
810    480         1
848    480         3
852    480         1
854    480        98
960    720         8
978    720         1
1264   720         2
1274   720         1
1280   718         1
       720       325
1440   1080        3
1920   1080      123
dtype: int64