In [1]:
import pandas as pd

clean_test_results_df = pd.read_csv("../results/clean_test_results.csv")
compressed_test_results_df = pd.read_csv("../results/compressed_test_results.csv")
validation_results_df = pd.read_csv("../results/validation_results.csv")

pd.set_option("display.max_colwidth",250)

In [2]:
validation_results_df

,model_name,focal,topk,augment,sampler,pos_weight,focal_alpha,topk_value,epochs,compression,...,fn,tp,real_precision,real_recall,real_f1,real_support,fake_precision,fake_recall,fake_f1,fake_support
0,best__e-10__augment-off__sampler-off__pos_weight-on,off,off,off,off,on,NaN,NaN,10,off,...,1799,19201,0.69,0.96,0.80,4200,0.99,0.91,0.95,21000
1,best__e-10__augment-off__sampler-on__pos_weight-off,off,off,off,on,off,NaN,NaN,10,off,...,1677,19323,0.70,0.95,0.81,4200,0.99,0.92,0.95,21000
2,best__e-10__augment-off__sampler-off__pos_weight-off,off,off,off,off,off,NaN,NaN,10,off,...,1771,19229,0.69,0.95,0.80,4200,0.99,0.92,0.95,21000
3,best__focal_loss-0.15_e-10__augment-on__sampler-off,on,off,on,off,NaN,0.15,NaN,10,off,...,1764,19236,0.69,0.94,0.80,4200,0.99,0.92,0.95,21000
4,best__e-10__augment-off__sampler-on__pos_weight-on,off,off,off,on,on,NaN,NaN,10,off,...,1300,19700,0.75,0.93,0.83,4200,0.99,0.94,0.96,21000
5,best__e-10__augment-on__sampler-off__pos_weight-off,off,off,on,off,off,NaN,NaN,10,off,...,1891,19109,0.68,0.94,0.79,4200,0.99,0.91,0.95,21000
6,best__topk-0.9_e-10__augment-on__sampler-off__pos_weight-on,off,on,on,off,on,NaN,0.9,10,off,...,1760,19240,0.69,0.95,0.80,4200,0.99,0.92,0.95,21000
7,best__focal_loss-0.15_e-10__augment-on__sampler-on,on,off,on,on,NaN,0.15,NaN,10,off,...,1759,19241,0.69,0.94,0.80,4200,0.99,0.92,0.95,21000
8,best__e-10__augment-on__sampler-off__pos_weight-on,off,off,on,off,on,NaN,NaN,10,off,...,1587,19413,0.71,0.93,0.80,4200,0.98,0.92,0.95,21000
9,best__e-10__augment-on__sampler-on__pos_weight-on,off,off,on,on,on,NaN,NaN,10,off,...,1726,19274,0.70,0.94,0.80,4200,0.99,0.92,0.95,21000
10,best__topk-0.9_e-10__augment-on__sampler-on__pos_weight-off,off,on,on,on,off,NaN,0.9,10,off,...,1946,19054,0.67,0.95,0.79,4200,0.99,0.91,0.95,21000
11,best__e-10__augment-on__sampler-on__pos_weight-off,off,off,on,on,off,NaN,NaN,10,off,...,1991,19009,0.67,0.94,0.78,4200,0.99,0.91,0.94,21000
12,best__focal_loss-0.25_e-10__augment-on__sampler-off,on,off,on,off,NaN,0.25,NaN,10,off,...,1905,19095,0.68,0.94,0.79,4200,0.99,0.91,0.95,21000
13,best__topk-0.8_e-10__augment-on__sampler-on__pos_weight-off,off,on,on,on,off,NaN,0.8,10,off,...,1706,19294,0.70,0.94,0.80,4200,0.99,0.92,0.95,21000
14,best__focal_loss-0.25_e-10__augment-on__sampler-on,on,off,on,on,NaN,0.25,NaN,10,off,...,2024,18976,0.66,0.95,0.78,4200,0.99,0.90,0.94,21000
15,best__topk-0.8_e-10__augment-on__sampler-off__pos_weight-on,off,on,on,off,on,NaN,0.8,10,off,...,2065,18935,0.66,0.95,0.78,4200,0.99,0.90,0.94,21000

In [3]:
combined_test_df = clean_test_results_df[["model_name", "auc"]].merge(compressed_test_results_df[["model_name", "auc"]],
                                                                     on="model_name", suffixes=("_clean", "_compressed"))

In [4]:
combined_test_df["gap"] = combined_test_df["auc_clean"] - combined_test_df["auc_compressed"]

In [5]:
combined_test_df.sort_values("auc_clean", ascending=False)

,model_name,auc_clean,auc_compressed,gap
0,best__e-10__augment-off__sampler-on__pos_weight-on,0.9914,0.9353,0.0561
1,best__e-10__augment-off__sampler-off__pos_weight-off,0.9902,0.9390,0.0512
2,best__e-10__augment-off__sampler-on__pos_weight-off,0.9901,0.9392,0.0509
3,best__e-10__augment-off__sampler-off__pos_weight-on,0.9890,0.9443,0.0447
4,best__focal_loss-0.15_e-10__augment-on__sampler-off,0.9871,0.9795,0.0076
5,best__e-10__augment-on__sampler-off__pos_weight-on,0.9867,0.9790,0.0077
6,best__focal_loss-0.15_e-10__augment-on__sampler-on,0.9864,0.9779,0.0085
7,best__focal_loss-0.25_e-10__augment-on__sampler-off,0.9859,0.9782,0.0077
8,best__focal_loss-0.25_e-10__augment-on__sampler-on,0.9859,0.9783,0.0076
9,best__topk-0.9_e-10__augment-on__sampler-on__pos_weight-off,0.9856,0.9768,0.0088
10,best__topk-0.8_e-10__augment-on__sampler-on__pos_weight-off,0.9852,0.9775,0.0077
11,best__topk-0.9_e-10__augment-on__sampler-off__pos_weight-on,0.9845,0.9764,0.0081
12,best__e-10__augment-on__sampler-off__pos_weight-off,0.9843,0.9758,0.0085
13,best__e-10__augment-on__sampler-on__pos_weight-off,0.9842,0.9748,0.0094
14,best__topk-0.8_e-10__augment-on__sampler-off__pos_weight-on,0.9829,0.9734,0.0095
15,best__e-10__augment-on__sampler-on__pos_weight-on,0.9828,0.9724,0.0104

In [6]:

validation_results_df[["model_name" ,"auc", "real_f1", "fake_f1", "compression"]].sort_values("auc", ascending=False)

,model_name,auc,real_f1,fake_f1,compression
0,best__e-10__augment-off__sampler-off__pos_weight-on,0.9824,0.80,0.95,off
1,best__e-10__augment-off__sampler-on__pos_weight-off,0.9822,0.81,0.95,off
2,best__e-10__augment-off__sampler-off__pos_weight-off,0.9814,0.80,0.95,off
3,best__focal_loss-0.15_e-10__augment-on__sampler-off,0.9814,0.80,0.95,off
4,best__e-10__augment-off__sampler-on__pos_weight-on,0.9803,0.83,0.96,off
5,best__e-10__augment-on__sampler-off__pos_weight-off,0.9802,0.79,0.95,off
6,best__topk-0.9_e-10__augment-on__sampler-off__pos_weight-on,0.9801,0.80,0.95,off
7,best__focal_loss-0.15_e-10__augment-on__sampler-on,0.9797,0.80,0.95,off
8,best__e-10__augment-on__sampler-off__pos_weight-on,0.9795,0.80,0.95,off
9,best__e-10__augment-on__sampler-on__pos_weight-on,0.9794,0.80,0.95,off
10,best__topk-0.9_e-10__augment-on__sampler-on__pos_weight-off,0.9788,0.79,0.95,off
11,best__e-10__augment-on__sampler-on__pos_weight-off,0.9787,0.78,0.94,off
12,best__focal_loss-0.25_e-10__augment-on__sampler-off,0.9781,0.79,0.95,off
13,best__topk-0.8_e-10__augment-on__sampler-on__pos_weight-off,0.9777,0.80,0.95,off
14,best__focal_loss-0.25_e-10__augment-on__sampler-on,0.9775,0.78,0.94,off
15,best__topk-0.8_e-10__augment-on__sampler-off__pos_weight-on,0.9763,0.78,0.94,off

In [7]:
combined_test_df = clean_test_results_df[["model_name", "auc","augment"]].merge(
            compressed_test_results_df[["model_name", "auc", "augment"]], on=["model_name", "augment"], suffixes=("_clean", "_compressed"))

In [10]:

combined_test_df["gap"] = combined_test_df["auc_clean"] - combined_test_df["auc_compressed"]
combined_test_df.sort_values(by="auc_compressed", ascending=False)

,model_name,auc_clean,augment,auc_compressed,gap
4,best__focal_loss-0.15_e-10__augment-on__sampler-off,0.9871,on,0.9795,0.0076
5,best__e-10__augment-on__sampler-off__pos_weight-on,0.9867,on,0.9790,0.0077
8,best__focal_loss-0.25_e-10__augment-on__sampler-on,0.9859,on,0.9783,0.0076
7,best__focal_loss-0.25_e-10__augment-on__sampler-off,0.9859,on,0.9782,0.0077
6,best__focal_loss-0.15_e-10__augment-on__sampler-on,0.9864,on,0.9779,0.0085
10,best__topk-0.8_e-10__augment-on__sampler-on__pos_weight-off,0.9852,on,0.9775,0.0077
9,best__topk-0.9_e-10__augment-on__sampler-on__pos_weight-off,0.9856,on,0.9768,0.0088
11,best__topk-0.9_e-10__augment-on__sampler-off__pos_weight-on,0.9845,on,0.9764,0.0081
12,best__e-10__augment-on__sampler-off__pos_weight-off,0.9843,on,0.9758,0.0085
13,best__e-10__augment-on__sampler-on__pos_weight-off,0.9842,on,0.9748,0.0094
14,best__topk-0.8_e-10__augment-on__sampler-off__pos_weight-on,0.9829,on,0.9734,0.0095
15,best__e-10__augment-on__sampler-on__pos_weight-on,0.9828,on,0.9724,0.0104
3,best__e-10__augment-off__sampler-off__pos_weight-on,0.9890,off,0.9443,0.0447
2,best__e-10__augment-off__sampler-on__pos_weight-off,0.9901,off,0.9392,0.0509
1,best__e-10__augment-off__sampler-off__pos_weight-off,0.9902,off,0.9390,0.0512
0,best__e-10__augment-off__sampler-on__pos_weight-on,0.9914,off,0.9353,0.0561

In [44]:
validation_seed_results_df = pd.read_csv("../results/validation_seed_results.csv")
validation_seed_results_df

,model_name,focal,topk,seed,augment,sampler,pos_weight,focal_alpha,topk_value,epochs,...,fn,tp,real_precision,real_recall,real_f1,real_support,fake_precision,fake_recall,fake_f1,fake_support
0,best__seed-3_e-10_augment-on_sampler-off_loss-focal_alpha-0.15736747005_gamma-2.0,on,off,3,on,off,NaN,NaN,NaN,10,...,1860,19140,0.68,0.95,0.79,4200,0.99,0.91,0.95,21000
1,best__seed-4_e-10_augment-on_sampler-off_loss-focal_alpha-0.15736747005_gamma-2.0,on,off,4,on,off,NaN,NaN,NaN,10,...,1769,19231,0.69,0.95,0.80,4200,0.99,0.92,0.95,21000
2,best__seed-2_e-10_augment-on_sampler-off_loss-bce_pw-0.15736747005,off,off,2,on,off,NaN,NaN,NaN,10,...,1693,19307,0.70,0.94,0.80,4200,0.99,0.92,0.95,21000
3,best__seed-1_e-10_augment-on_sampler-off_loss-bce_pw-0.15736747005,off,off,1,on,off,NaN,NaN,NaN,10,...,1843,19157,0.68,0.94,0.79,4200,0.99,0.91,0.95,21000
4,best__seed-3_e-10_augment-on_sampler-off_loss-bce_pw-0.15736747005,off,off,3,on,off,NaN,NaN,NaN,10,...,1638,19362,0.71,0.94,0.81,4200,0.99,0.92,0.95,21000
5,best__seed-2_e-10_augment-on_sampler-off_loss-focal_alpha-0.15736747005_gamma-2.0,on,off,2,on,off,NaN,NaN,NaN,10,...,1956,19044,0.67,0.95,0.79,4200,0.99,0.91,0.95,21000
6,best__seed-5_e-10_augment-on_sampler-off_loss-focal_alpha-0.15736747005_gamma-2.0,on,off,5,on,off,NaN,NaN,NaN,10,...,1929,19071,0.67,0.94,0.79,4200,0.99,0.91,0.95,21000
7,best__seed-1_e-10_augment-on_sampler-off_loss-focal_alpha-0.15736747005_gamma-2.0,on,off,1,on,off,NaN,NaN,NaN,10,...,1911,19089,0.68,0.95,0.79,4200,0.99,0.91,0.95,21000
8,best__seed-5_e-10_augment-on_sampler-off_loss-bce_pw-0.15736747005,off,off,5,on,off,NaN,NaN,NaN,10,...,2163,18837,0.65,0.95,0.77,4200,0.99,0.90,0.94,21000
9,best__seed-4_e-10_augment-on_sampler-off_loss-bce_pw-0.15736747005,off,off,4,on,off,NaN,NaN,NaN,10,...,2170,18830,0.65,0.96,0.77,4200,0.99,0.90,0.94,21000

In [55]:
validation_seed_results_df.groupby("focal")["auc"].agg(["mean", "std", "min", "max"])

          mean       std     min     max
focal
off    0.97922  0.001551  0.9775  0.9807
on     0.97960  0.001347  0.9779  0.9811

In [57]:
validation_seed_results_df[["model_name", "auc","focal"]].sort_values("auc", ascending = False)

,model_name,auc,focal
0,best__seed-3_e-10_augment-on_sampler-off_loss-focal_alpha-0.15736747005_gamma-2.0,0.9811,on
1,best__seed-4_e-10_augment-on_sampler-off_loss-focal_alpha-0.15736747005_gamma-2.0,0.9808,on
2,best__seed-2_e-10_augment-on_sampler-off_loss-bce_pw-0.15736747005,0.9807,off
3,best__seed-1_e-10_augment-on_sampler-off_loss-bce_pw-0.15736747005,0.9804,off
4,best__seed-3_e-10_augment-on_sampler-off_loss-bce_pw-0.15736747005,0.9799,off
5,best__seed-2_e-10_augment-on_sampler-off_loss-focal_alpha-0.15736747005_gamma-2.0,0.9794,on
6,best__seed-5_e-10_augment-on_sampler-off_loss-focal_alpha-0.15736747005_gamma-2.0,0.9788,on
7,best__seed-1_e-10_augment-on_sampler-off_loss-focal_alpha-0.15736747005_gamma-2.0,0.9779,on
8,best__seed-5_e-10_augment-on_sampler-off_loss-bce_pw-0.15736747005,0.9776,off
9,best__seed-4_e-10_augment-on_sampler-off_loss-bce_pw-0.15736747005,0.9775,off

In [54]:
validation_results_df[["model_name", "auc"]].sort_values("auc", ascending = False)

                                                     model_name     auc
0           best__e-10__augment-off__sampler-off__pos_weight-on  0.9824
1           best__e-10__augment-off__sampler-on__pos_weight-off  0.9822
2          best__e-10__augment-off__sampler-off__pos_weight-off  0.9814
3           best__focal_loss-0.15_e-10__augment-on__sampler-off  0.9814
4            best__e-10__augment-off__sampler-on__pos_weight-on  0.9803
5           best__e-10__augment-on__sampler-off__pos_weight-off  0.9802
6   best__topk-0.9_e-10__augment-on__sampler-off__pos_weight-on  0.9801
7            best__focal_loss-0.15_e-10__augment-on__sampler-on  0.9797
8            best__e-10__augment-on__sampler-off__pos_weight-on  0.9795
9             best__e-10__augment-on__sampler-on__pos_weight-on  0.9794
10  best__topk-0.9_e-10__augment-on__sampler-on__pos_weight-off  0.9788
11           best__e-10__augment-on__sampler-on__pos_weight-off  0.9787
12          best__focal_loss-0.25_e-10__augment-on__sampler-off  0.9781
13  best__topk-0.8_e-10__augment-on__sampler-on__pos_weight-off  0.9777
14           best__focal_loss-0.25_e-10__augment-on__sampler-on  0.9775
15  best__topk-0.8_e-10__augment-on__sampler-off__pos_weight-on  0.9763

In [50]:
compressed_validation_seed_results_df = pd.read_csv("../results/compressed_validation_seed_results.csv")
compressed_validation_seed_results_df[["model_name","auc"]]validation_seed_results_df.groupby("focal")["auc"].agg(["mean", "std", "min", "max"])

,model_name,auc
0,best__seed-3_e-10_augment-on_sampler-off_loss-focal_alpha-0.15736747005_gamma-2.0,0.9729
1,best__seed-3_e-10_augment-on_sampler-off_loss-bce_pw-0.15736747005,0.9712
2,best__seed-4_e-10_augment-on_sampler-off_loss-focal_alpha-0.15736747005_gamma-2.0,0.9709
3,best__seed-1_e-10_augment-on_sampler-off_loss-bce_pw-0.15736747005,0.9699
4,best__seed-5_e-10_augment-on_sampler-off_loss-focal_alpha-0.15736747005_gamma-2.0,0.9693
5,best__seed-2_e-10_augment-on_sampler-off_loss-bce_pw-0.15736747005,0.9693
6,best__seed-2_e-10_augment-on_sampler-off_loss-focal_alpha-0.15736747005_gamma-2.0,0.9692
7,best__seed-4_e-10_augment-on_sampler-off_loss-bce_pw-0.15736747005,0.9689
8,best__seed-1_e-10_augment-on_sampler-off_loss-focal_alpha-0.15736747005_gamma-2.0,0.9678
9,best__seed-5_e-10_augment-on_sampler-off_loss-bce_pw-0.15736747005,0.9674

In [53]:
compressed_validation_seed_results_df.groupby("focal")["auc"].agg(["mean", "std", "min", "max"])

          mean       std     min     max
focal
off    0.96934  0.001390  0.9674  0.9712
on     0.97002  0.001949  0.9678  0.9729